package fr.dahus.foodplanner.restapi.model;
// Generated 31 oct. 2017 23:03:17 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Daylist generated by hbm2java
 */
@Entity
@Table(name = "daylist", schema = "public")
public class Daylist implements java.io.Serializable {

	private static final long serialVersionUID = -2681208588032735060L;
	private long id;
	private String title;
	private Set<Day> days = new HashSet<Day>(0);

	public Daylist() {
	}

	public Daylist(long id) {
		this.id = id;
	}

	public Daylist(long id, String title, Set<Day> days) {
		this.id = id;
		this.title = title;
		this.days = days;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "title", length = 32)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "daylist")
	public Set<Day> getDays() {
		return this.days;
	}

	public void setDays(Set<Day> days) {
		this.days = days;
	}

}
